package fr.lacaleche.glue.shaper;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.mojang.serialization.JsonOps;
import fr.lacaleche.glue.block.Rotation16;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.IntegerProperty;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.shapes.BooleanOp;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.VoxelShape;
import org.jetbrains.annotations.Nullable;
import org.joml.Matrix4f;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

/**
 * Generates block shapes from block models, for {@link BlockShapes}.
 *
 * <p>For each state of a declared block, the provider resolves the models its blockstate file draws
 * (variant or multipart), applies their blockstate rotation, and converts the model elements into a
 * shape; see {@link ShapeGeometry#toShape} for how rotated elements become boxes. Models and
 * blockstates are read as JSON: from this data run's output (models generated by an earlier
 * provider), the mod's resources, any {@link #modelRoot} and finally the classpath. Add this
 * provider after the providers that generate those models.</p>
 *
 * <pre>{@code
 * public final class MyShapes extends BlockShapeProvider {
 *     public MyShapes(FabricDataOutput output) {
 *         super(output);
 *     }
 *
 *     @Override
 *     protected void generate() {
 *         block(MyBlocks.STOVE).collision(MyMod.id("block/stove_collision"));
 *         block(MyBlocks.CHAIR).rotation16(BlockStateProperties.ROTATION_16);
 *     }
 * }
 * }</pre>
 *
 * <p>Generation fails on a missing blockstate or model, a property the blockstate file does not
 * know, or a state no variant matches.</p>
 */
public abstract class BlockShapeProvider implements DataProvider {

    private final FabricDataOutput output;
    private final Map<Block, Rule> rules = new LinkedHashMap<>();
    private final List<Path> modelRoots = new ArrayList<>();

    protected BlockShapeProvider(FabricDataOutput output) {
        this.output = output;
    }

    @Override
    public CompletableFuture<?> run(CachedOutput cache) {
        generate();

        List<Path> roots = new ArrayList<>();
        roots.add(this.output.getOutputFolder());
        roots.addAll(this.output.getModContainer().getRootPaths());
        roots.addAll(this.modelRoots);
        ModelSource source = new ModelSource(roots);

        List<CompletableFuture<?>> writes = new ArrayList<>();
        for (Map.Entry<Block, Rule> entry : this.rules.entrySet()) {
            ResourceLocation id = BuiltInRegistries.BLOCK.getKey(entry.getKey());
            JsonElement json = BlockShapesFile.CODEC.encodeStart(JsonOps.INSTANCE, shapesFile(entry.getKey(), id, entry.getValue(), source))
                    .getOrThrow(message -> new IllegalStateException("Cannot encode the shapes of " + id + ": " + message));
            Path path = this.output.getOutputFolder()
                    .resolve(BlockShapes.DIRECTORY)
                    .resolve(id.getNamespace())
                    .resolve(id.getPath() + ".json");
            writes.add(DataProvider.saveStable(cache, json, path));
        }
        return CompletableFuture.allOf(writes.toArray(CompletableFuture[]::new));
    }

    @Override
    public String getName() {
        return "Glue block shapes";
    }

    /** Declares the blocks to generate, with {@link #block} and {@link #modelRoot}. */
    protected abstract void generate();

    /** Generates shapes for {@code block}; the returned rule refines how. */
    protected final Rule block(Block block) {
        return this.rules.computeIfAbsent(block, Rule::new);
    }

    /**
     * Another directory holding {@code assets/}, searched for models and blockstates after the mod's
     * own resources, such as a development resource pack with a mod's parent models.
     */
    protected final void modelRoot(Path root) {
        this.modelRoots.add(root);
    }

    private static BlockShapesFile shapesFile(Block block, ResourceLocation id, Rule rule, ModelSource source) {
        JsonObject blockstate = source.blockstate(id);
        List<List<AABB>> shapes = new ArrayList<>();
        Map<List<AABB>, Integer> indices = new HashMap<>();
        List<List<GeometryBox>> geometries = new ArrayList<>();
        Map<ResourceLocation, Integer> geometryIndices = new HashMap<>();
        Map<String, BlockShapesFile.StateShapes> states = new LinkedHashMap<>();

        for (BlockState state : block.getStateDefinition().getPossibleStates()) {
            List<BlockstateResolver.Placement> placements = BlockstateResolver.resolve(blockstate, properties(state), id.toString());
            float turn = rule.turn(state);
            Matrix4f extraRotation = new Matrix4f().rotationY((float) Math.toRadians(-turn));

            int outline = index(shape(placements, null, extraRotation, rule.resolution, source), shapes, indices);
            int collisionIndex = index(shape(placements, rule.collisionModel, extraRotation, rule.collisionResolution, source), shapes, indices);
            Optional<Integer> collision = collisionIndex == outline ? Optional.empty() : Optional.of(collisionIndex);

            List<BlockShapesFile.PlacedModel> models = new ArrayList<>();
            List<BlockShapesFile.PlacedModel> collisionModels = new ArrayList<>();
            for (BlockstateResolver.Placement placement : placements) {
                models.add(placed(placement, placement.model(), turn, source, geometries, geometryIndices));
                if (rule.collisionModel != null) {
                    collisionModels.add(placed(placement, rule.collisionModel, turn, source, geometries, geometryIndices));
                }
            }
            states.put(BlockShapes.stateKey(state), new BlockShapesFile.StateShapes(outline, collision, models, collisionModels));
        }
        return new BlockShapesFile(shapes, geometries, rule.collisionResolution, states);
    }

    /** {@code model} where {@code placement} stands, its geometry written once per file. */
    private static BlockShapesFile.PlacedModel placed(BlockstateResolver.Placement placement, ResourceLocation model, float turn,
                                                      ModelSource source, List<List<GeometryBox>> geometries,
                                                      Map<ResourceLocation, Integer> geometryIndices) {
        int geometry = geometryIndices.computeIfAbsent(model, unused -> {
            geometries.add(source.geometry(model).boxes());
            return geometries.size() - 1;
        });
        return new BlockShapesFile.PlacedModel(geometry, placement.x().ordinal() * 90, placement.y().ordinal() * 90, turn);
    }

    /**
     * The union of the placed models; with {@code model}, that model drawn at each placement's
     * rotation instead of the placement's own model.
     */
    static VoxelShape shape(List<BlockstateResolver.Placement> placements, @Nullable ResourceLocation model,
                                    Matrix4f extraRotation, int resolution, ModelSource source) {
        VoxelShape shape = Shapes.empty();
        for (BlockstateResolver.Placement placement : placements) {
            Matrix4f transform = ShapeGeometry.aboutCentre(new Matrix4f(extraRotation).mul(placement.rotation()));
            ShapeGeometry geometry = source.geometry(model != null ? model : placement.model());
            shape = Shapes.joinUnoptimized(shape, geometry.toShape(transform, resolution), BooleanOp.OR);
        }
        return shape.optimize();
    }

    private static int index(VoxelShape shape, List<List<AABB>> shapes, Map<List<AABB>, Integer> indices) {
        List<AABB> boxes = shape.toAabbs();
        return indices.computeIfAbsent(boxes, unused -> {
            shapes.add(boxes);
            return shapes.size() - 1;
        });
    }

    private static Map<String, String> properties(BlockState state) {
        Map<String, String> properties = new HashMap<>();
        state.getValues().forEach((property, value) -> properties.put(property.getName(), BlockShapes.valueName(property, value)));
        return properties;
    }

    /** How the shapes of one block are generated. */
    public static final class Rule {

        /**
         * Voxels per block for collision where a rotation leaves elements unaligned: coarser than
         * the outline, since entities need no pixel detail and every coordinate a shape adds makes
         * its collision checks slower.
         */
        public static final int DEFAULT_COLLISION_RESOLUTION = 8;

        private final Block block;
        private @Nullable ResourceLocation collisionModel;
        private @Nullable IntegerProperty rotation16;
        private int resolution = ShapeGeometry.DEFAULT_RESOLUTION;
        private int collisionResolution = DEFAULT_COLLISION_RESOLUTION;

        private Rule(Block block) {
            this.block = block;
        }

        /**
         * Collision from another model, usually simpler than the drawn one, placed and rotated like
         * the drawn models. Without it, collision is the drawn models at the collision resolution.
         */
        public Rule collision(ResourceLocation model) {
            this.collisionModel = model;
            return this;
        }

        /**
         * Turns each state by {@code property} in steps of 22.5 degrees, in the same direction as a
         * blockstate {@code y} rotation, on top of its blockstate rotation: for blocks whose model is
         * turned by such a property outside the blockstate file, as {@link Rotation16} blocks are by
         * {@code GlueBlockModels.rotation16} on the client.
         *
         * @throws IllegalArgumentException if the block lacks the property or it is not 0 to 15
         */
        public Rule rotation16(IntegerProperty property) {
            if (!this.block.getStateDefinition().getProperties().contains(property)) {
                throw new IllegalArgumentException(this.block + " has no property " + property.getName());
            }
            this.rotation16 = Rotation16.check(property);
            return this;
        }

        /**
         * Voxels per block for the outline shape where a rotation leaves elements unaligned; see
         * {@link ShapeGeometry#toShape}. A {@code GlueBlock}'s drawn outline and ray casts follow its
         * model exactly; this shape is what code reading {@code getShape} sees.
         */
        public Rule resolution(int resolution) {
            this.resolution = checkResolution(resolution);
            return this;
        }

        /** Voxels per block for collision where a rotation leaves elements unaligned; see {@link #DEFAULT_COLLISION_RESOLUTION}. */
        public Rule collisionResolution(int resolution) {
            this.collisionResolution = checkResolution(resolution);
            return this;
        }

        private float turn(BlockState state) {
            return this.rotation16 == null ? 0f : Rotation16.degrees(state.getValue(this.rotation16));
        }

        private static int checkResolution(int resolution) {
            if (resolution < 1 || resolution > ShapeVoxelizer.MAX_RESOLUTION) {
                throw new IllegalArgumentException("Resolution must be between 1 and " + ShapeVoxelizer.MAX_RESOLUTION);
            }
            return resolution;
        }
    }
}
